config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :price_btcs, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/price_btc.rb
require 'coinbase/wallet'

class PriceBtc < ApplicationRecord
  before_save :save_prices

  def save_prices
    client = Coinbase::Wallet::Client.new(api_key: ENV["COINBASE_KEY"],
                                           api_secret: ENV["COINBASE_SECRET"])
    self.buy = self.class.get_buy_price(client)
    self.sell = self.class.get_sell_price(client)
    self.spot = self.class.get_spot_price(client)
  end

  def self.get_buy_price(client)
    binding.pry
    client.buy_price({currency_pair: 'BTC-USD'})["amount"].to_f
  end

  def self.get_sell_price(client)
    client.sell_price({currency_pair: 'BTC-USD'})["amount"].to_f
  end

  def self.get_spot_price(client)
    client.spot_price({currency_pair: 'BTC-USD'})["amount"].to_f
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/price_btcs_controller.rb
class PriceBtcsController < ApplicationController
  def index
    @prices = PriceBtc.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= link_to("View Price Index", price_btcs_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoinbaseFuckery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/price_btcs/index.html.erb
<div class="wrapper">
  <div class="row justify-content-md-center">
    <div class="col col-lg-6">
      <p>Buy Price: <%= PriceBtc.get_buy_price %></p>
      <%= line_chart PriceBtc.group_by_hour(:created_at).average(:buy) %>
    </div>
    <div class="col col-lg-6">
      <p>Sell Price: $<%= PriceBtc.get_sell_price %></p>
      <%= line_chart PriceBtc.group_by_hour(:created_at).average(:sell) %>
    </div>
  </div>
</div>